version: '3.8'

services:
  redis:
    container_name: diariest_redis
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - '6379:6379'

  postgresql:
    container_name: diariest_psql
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=diariest
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=diariest
    ports:
      - '5438:5432'